### ISSUE TITLE
Burrow Install - undefined: sync.Map

### ISSUE THREAD

**Issue by hsaif** [linkedin/Burrow#301]
Running `go get github.com/linkedin/Burrow` resulted in the following:

`# github.com/linkedin/Burrow/core/internal/cluster
src/github.com/linkedin/Burrow/core/internal/cluster/kafka_cluster.go:224: undefined: sync.Map`

Any ideas?

**Comment by Alxirs** [comment]
Same problem.

**Comment by kpocius** [comment]
`sync.Map` is only available in go 1.9 and higher. My bet is you're trying to compile using go 1.8.*

**Comment by toddpalino** [comment]
Yeah, make sure you're using golang 1.9
